# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
      AppBundle\Entity\User:
          algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:

        db_provider:
              entity:
                 class: AppBundle:User
                 property: username
#        our_users:
#           entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            logout:
               path: /logout

            guard:
                authenticators:
                  - app.security.login_form_authenticator

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_MANAGER}
        - { path: ^/$, roles: ROLE_MANAGER }

